version: "3"

services:
  coldfront-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: knikolla/coldfront:latest
    environment:
      DEBUG: "True"
      INITIAL_SETUP: "True"
      LOAD_TEST_DATA: "True"
      SECRET_KEY: "klajsfkljasdfkljasdfkljadsfjklads"
      DATABASE_ENGINE: 'django.db.backends.mysql'
      DATABASE_HOST: 'coldfront-database'
      DATABASE_PORT: 3306
      DATABASE_NAME: 'coldfront'
      DATABASE_USER: 'coldfront'
      DATABASE_PASSWORD: 'nomoresecret'
      OPENSTACK_DEVSTACK_APPLICATION_CREDENTIAL_ID: ""
      OPENSTACK_DEVSTACK_APPLICATION_CREDENTIAL_SECRET: ""
      PLUGIN_AUTH_OIDC: "True"
      PLUGIN_MOKEY: "True"
      OIDC_RP_SIGN_ALGO: RS256
      OIDC_RP_SCOPES: "openid email profile"
      OIDC_RP_CLIENT_ID: coldfront
      OIDC_RP_CLIENT_SECRET: "XuQyzzExN4jmaimfjPLnOymQxdInzApT"
      OIDC_OP_AUTHORIZATION_ENDPOINT: "http://keycloak:8080/realms/master/protocol/openid-connect/auth"
      OIDC_OP_TOKEN_ENDPOINT: "http://keycloak:8080/realms/master/protocol/openid-connect/token"
      OIDC_OP_USER_ENDPOINT: "http://keycloak:8080/realms/master/protocol/openid-connect/userinfo"
      OIDC_OP_JWKS_ENDPOINT: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
      OIDC_VERIFY_SSL: "False"
      KEYCLOAK_URL: "http://keycloak:8080"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASS: "nomoresecret"
      KEYCLOAK_REALM: "master"
      ADDITIONAL_USER_SEARCH_CLASSES: "coldfront_plugin_keycloak_usersearch.search.KeycloakUserSearch"
      REDIS_HOST: "coldfront-redis"
      CENTER_NAME: "New England Research Cloud"
      CENTER_HELP_URL: "https://nerc.mghpcc.org/user-guides/"
      ACCOUNT_CREATION_TEXT: >
        Any faculty, staff, student, or external collaborator must request an user account through the <a href="https://regapp.mss.mghpcc.org/" target="_blank">MGHPCC Shared Services (MGHPCC-SS) Account Portal</a>. For more information, please see the <a href="https://nerc.mghpcc.org/user-guides/" target="_blank">user guides</a>.
    ports:
      - "8081:8080"

  coldfront-database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: nomoresecret
      MYSQL_DATABASE: coldfront
      MYSQL_USER: coldfront
      MYSQL_PASSWORD: nomoresecret

  coldfront-redis:
    image: redis:6.2

  coldfront-workers:
    build:
      context: .
      dockerfile: Dockerfile
    image: knikolla/coldfront:latest
    environment:
      DEBUG: "True"
      INITIAL_SETUP: "True"
      LOAD_TEST_DATA: "True"
      SECRET_KEY: "klajsfkljasdfkljasdfkljadsfjklads"
      DATABASE_ENGINE: 'django.db.backends.mysql'
      DATABASE_HOST: 'coldfront-database'
      DATABASE_PORT: 3306
      DATABASE_NAME: 'coldfront'
      DATABASE_USER: 'coldfront'
      DATABASE_PASSWORD: 'nomoresecret'
      OPENSTACK_DEVSTACK_APPLICATION_CREDENTIAL_ID: ""
      OPENSTACK_DEVSTACK_APPLICATION_CREDENTIAL_SECRET: ""
      PLUGIN_AUTH_OIDC: "True"
      PLUGIN_MOKEY: "True"
      OIDC_RP_SIGN_ALGO: RS256
      OIDC_RP_SCOPES: "openid email profile"
      OIDC_RP_CLIENT_ID: coldfront
      OIDC_RP_CLIENT_SECRET: "XuQyzzExN4jmaimfjPLnOymQxdInzApT"
      OIDC_OP_AUTHORIZATION_ENDPOINT: "http://keycloak:8080/realms/master/protocol/openid-connect/auth"
      OIDC_OP_TOKEN_ENDPOINT: "http://keycloak:8080/realms/master/protocol/openid-connect/token"
      OIDC_OP_USER_ENDPOINT: "http://keycloak:8080/realms/master/protocol/openid-connect/userinfo"
      OIDC_OP_JWKS_ENDPOINT: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
      OIDC_VERIFY_SSL: "False"
      KEYCLOAK_URL: "http://keycloak:8080"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASS: "nomoresecret"
      KEYCLOAK_REALM: "master"
      ADDITIONAL_USER_SEARCH_CLASSES: "coldfront_plugin_keycloak_usersearch.search.KeycloakUserSearch"
      REDIS_HOST: "coldfront-redis"
    command: ["python", "-m", "django", "qcluster"]

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: nomoresecret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: nomoresecret
      DB_VENDOR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: "nomoresecret"
      DB_ADDR: "keycloak-database"
      JAVA_OPTS: "-server -Xms128m -Xmx1024m -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true"
    ports:
      - "8080:8080"  # host:container
      - "8443:8443"
    command: ["start-dev", "--log-level=DEBUG"]

  keycloak-database:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: nomoresecret
