version: "3"

services:
  coldfront-dev:
    container_name: coldfront
    build:
      context: .
      dockerfile: Dockerfile
    image: knikolla/coldfront:latest
    ports:
      - "8080:8080"  # host:container
    environment:
      DEBUG: "True"
      DB_HOST: coldfront-database
      DB_URL: mysql://coldfront:nomoresecret@coldfront-database:3306/coldfront
      OPENSTACK_DEVSTACK_APPLICATION_CREDENTIAL_ID: ""
      OPENSTACK_DEVSTACK_APPLICATION_CREDENTIAL_SECRET: ""

  coldfront-database:
    container_name: coldfront-mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: nomoresecret
      MYSQL_DATABASE: coldfront
      MYSQL_USER: coldfront
      MYSQL_PASSWORD: nomoresecret
    ports:
      - "3306:3306"