namespace: coldfront
resources:
  - configmap.yaml
  - secrets.yaml
  - ha-postgres.yaml
  - ../../base
  - routes/app.yaml
  - routes/static-files.yaml
patchesStrategicMerge:
  - patches/coldfront-deployment.yaml
