apiVersion: apps/v1
kind: Deployment
metadata:
  name: coldfront-deployment
spec:
  template:
    spec:
      containers:
      - name: coldfront
        envFrom:
        - configMapRef:
            name: coldfront-configmap
        - secretRef:
            name: coldfront-secrets
