apiVersion: apps/v1
kind: Deployment
metadata:
  name: coldfront-deployment
spec:
  template:
    spec:
      containers:
      - name: coldfront
        env:
          - name: _DB_USER
            valueFrom:
              secretKeyRef:
                name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                key: user
          - name: _DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                key: password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                key: host
          - name: _DB_NAME
            valueFrom:
              secretKeyRef:
                name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                key: dbname
          - name: DB_URL
            value: psql://$(_DB_USER):$(_DB_PASSWORD)@$(DB_HOST)/$(_DB_NAME)
        envFrom:
        - configMapRef:
            name: coldfront-configmap
        - secretRef:
            name: coldfront-secrets
