apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: coldfront-static-files
spec:
  host: 'coldfront.apps.nerc-shift-1.rc.fas.harvard.edu'
  path: '/static'
  port:
    targetPort: http
  to:
    kind: Service
    name: coldfront-static-files
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
