apiVersion: v1
kind: ConfigMap
metadata:
  name: coldfront-configmap
data:
  DEBUG: "True"
  DB_HOST: "database-mariadb"
  DB_URL: "mysql://coldfront:nomoresecret@database-mariadb:3306/coldfront"
  OPENSTACK_DEVSTACK_APPLICATION_CREDENTIAL_ID: ""
  OPENSTACK_DEVSTACK_APPLICATION_CREDENTIAL_SECRET: ""
