apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: coldfront-postgres-ha
spec:
  image: default-route-openshift-image-registry.apps.nerc-shift-1.rc.fas.harvard.edu/postgres-operator/crunchy-postgres:latest
  postgresVersion: 13
  instances:
    - name: pgha1
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 5Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: coldfront-postgres-ha
                  postgres-operator.crunchydata.com/instance-set: pgha1
  backups:
    pgbackrest:
      image: default-route-openshift-image-registry.apps.nerc-shift-1.rc.fas.harvard.edu/postgres-operator/crunchy-pgbackrest:latest
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 5Gi
  proxy:
    pgBouncer:
      image: default-route-openshift-image-registry.apps.nerc-shift-1.rc.fas.harvard.edu/postgres-operator/crunchy-pgbouncer:latest
      replicas: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: coldfront-postgres-ha
                  postgres-operator.crunchydata.com/role: pgbouncer
